### PR TITLE
Finished about_us.

### PR DESCRIPTION
**Pull request by LucaPetrocchi**
As the title says. Took me an unbearably long amount of time to make work for something so simple, but it works.

### CODE REVIEW

**Review by FacundoEsteban-Lemo — COMMENTED** [review]
Where is the html my brother 🔥 🔥 🔥 🔥

**Comment by valentinoarballo** [comment]
🗣️who let him cook⁉️🔥

**Comment by LucaPetrocchi** [comment]
i fix

**Review by FacundoEsteban-Lemo — APPROVED** [review]
confío ciegamente :+1:

**Review by nazabucciarelliITEC — APPROVED** [review]

**Pull request merged**
